#include <components/resources/dataheaders/es3_shaders.h>

namespace ngs {

const char* es3_model_view_project_vert = "#version 330\n"
    "layout(std140) uniform Inputs\n"
    "{\n"
    "    mat4 model_view;\n"
    "    mat4 projection;\n"
    "    mat4 model_view_projection;\n"
    "    uniform vec4 tint_color;\n"
    "};\n"
    "in vec4 position;\n"
    "in vec3 normal;\n"
    "in vec2 tex_coord;\n"
    "out VertexAttributes\n"
    "{\n"
    "    smooth vec2 tex_coord;\n"
    "    smooth vec3 normal;\n"
    "} attr_out;\n"
    "void main()\n"
    "{ \n"
    "    gl_Position = model_view_projection*position;\n"
    "    attr_out.normal=normal;\n"
    "    attr_out.tex_coord=tex_coord;\n"
    "    //gl_Position = gl_ModelVieProjectionMatrix*position;\n"
    "    //gl_Position=gl_ModelViewProjectionMatrix*gl_vertex;\n"
    "    //gl_Position=ftransform();\n"
    "}\n";

const char* es3_floating_texture_value_frag = "#version 330\n"
    "// Uniforms\n"
    "layout(std140) uniform Inputs\n"
    "{\n"
    "    mat4 model_view;\n"
    "    mat4 projection;\n"
    "    mat4 model_view_projection;\n"
    "    uniform vec4 tint_color;\n"
    "};\n"
    "uniform sampler2D image_texture;\n"
    "// Outputs\n"
    "layout(location=0) out vec4 output_color;\n"
    "// Inputs\n"
    "in VertexAttributes\n"
    "{\n"
    "    smooth vec2 tex_coord;\n"
    "    smooth vec3 normal;\n"
    "} attr_in;\n"
    "void main()\n"
    "{\n"
    "    vec4 temp=texture(image_texture,attr_in.tex_coord).xyzw;\n"
    "    output_color=temp+tint_color;\n"
    "}\n";

//const char* es3_floating_texture_value_frag = "#version 330\n"
//    "// Uniforms\n"
//    "layout(std140) uniform Inputs\n"
//    "{\n"
//    "    mat4 model_view;\n"
//    "    mat4 projection;\n"
//    "    mat4 model_view_projection;\n"
//    "    uniform vec4 tint_color;\n"
//    "};\n"
//    "uniform sampler2D image_texture;\n"
//    "// Outputs\n"
//    "layout(location=0) out vec4 output_color;\n"
//    "// Inputs\n"
//    "in VertexAttributes\n"
//    "{\n"
//    "    smooth vec3 normal;\n"
//    "    smooth vec2 tex_coord;\n"
//    "} attr_in;\n"
//    "void main()\n"
//    "{\n"
//    "    vec4 temp=texture(image_texture,attr_in.tex_coord).xyzw;\n"
//    "    output_color=temp+tint_color;\n"
//    "}\n";

const char* es3_int_texture_value_frag = "#version 330\n"
    "layout(std140) uniform Inputs\n"
    "{\n"
    "    mat4 model_view;\n"
    "    mat4 projection;\n"
    "    mat4 model_view_projection;\n"
    "    uniform vec4 tint_color;\n"
    "};\n"
    "uniform isampler2D image_texture;\n"
    "layout(location=0) out ivec4 output_color;\n"
    "in VertexAttributes\n"
    "{\n"
    "    smooth vec2 tex_coord;\n"
    "    smooth vec3 normal;\n"
    "} attr_in;\n"
    "void main()\n"
    "{\n"
    "    output_color=texture(image_texture,attr_in.tex_coord).xyzw;\n"
    "    output_color+=ivec4(tint_color);\n"
    "}\n";

const char* es3_uint_texture_value_frag = "#version 330\n"
  "layout(std140) uniform Inputs\n"
  "{\n"
  "    mat4 model_view;\n"
  "    mat4 projection;\n"
  "    mat4 model_view_projection;\n"
  "    uniform vec4 tint_color;\n"
  "};\n"
  "uniform usampler2D image_texture;\n"
  "layout(location=0) out uvec4 output_color;\n"
  "in VertexAttributes\n"
  "{\n"
  "    smooth vec2 tex_coord;\n"
  "    smooth vec3 normal;\n"
  "} attr_in;\n"
  "void main()\n"
  "{\n"
  "    output_color=texture(image_texture,attr_in.tex_coord).xyzw;\n"
  "    output_color+=uvec4(tint_color);\n"
  "}\n";




const char* es3_triangle_pass_through_geom = "#version 330\n"
    "layout(triangles) in;\n"
    "layout(triangle_strip) out;\n"
    "layout(max_vertices = 30) out;\n"
    "in VertexAttributes\n"
    "{\n"
    "    vec2 tex_coord;\n"
    "    vec3 normal;\n"
    "} attr_in[];\n"
    "out VertexAttributes\n"
    "{\n"
    "    smooth vec2 tex_coord;\n"
    "    smooth vec3 normal;\n"
    "} attr_out;\n"
    "void main()\n"
    "{\n"
    "    for(int i=0; i<3; i++)\n"
    "    {\n"
    "        gl_Position=gl_in[i].gl_Position;\n"
    "        attr_out.normal=attr_in[i].normal;\n"
    "        attr_out.tex_coord=attr_in[i].tex_coord;\n"
    "        EmitVertex();\n"
    "    }\n"
    "    EndPrimitive();\n"
    "}\n";

const char* es3_multisampling_frag = "#version 330\n"
    "// Uniforms\n"
    "layout(std140) uniform Inputs\n"
    "{\n"
    "    mat4 model_view;\n"
    "    mat4 projection;\n"
    "    mat4 model_view_projection;\n"
    "    uniform vec4 tint_color;\n"
    "};\n"
    "uniform sampler2D image_texture;\n"
    "// Outputs\n"
    "layout(location=0) out vec4 output_color;\n"
    "// Inputs\n"
    "in VertexAttributes\n"
    "{\n"
    "    smooth vec2 tex_coord;\n"
    "    smooth vec3 normal;\n"
    "} attr_in;\n"
    "void main()\n"
    "{\n"
    "    output_color=texture(image_texture,attr_in.tex_coord).xyzw;\n"
    "    // Debugging\n"
    "    /*\n"
    "    output_color=vec4(0.0);\n"
    "    if(smooth_tex_coord.x<0.0)\n"
    "    {\n"
    "        output_color+=vec4(-10,0,0,0);\n"
    "    }\n"
    "    if(smooth_tex_coord.y<0.0)\n"
    "    {\n"
    "        output_color+=vec4(0,smooth_tex_coord.y,0,0);\n"
    "    }\n"
    "    if(smooth_tex_coord.x>1.0)\n"
    "    {\n"
    "        output_color+=vec4(0,0,10,0);\n"
    "    }\n"
    "    if(smooth_tex_coord.y>1.0)\n"
    "    {\n"
    "        output_color+=vec4(0,0,0,10);\n"
    "    }\n"
    "    */\n"
    "}\n";

const char* es3_centroid_model_view_project_vert = "#version 330\n"
"layout(std140) uniform Inputs\n"
"{\n"
"    mat4 model_view;\n"
"    mat4 projection;\n"
"    mat4 model_view_projection;\n"
"};\n"
"in vec4 position;\n"
"in vec3 normal;\n"
"in vec2 tex_coord;\n"
"out VertexAttributes\n"
"{\n"
"    smooth centroid vec2 tex_coord;\n"
"    smooth centroid vec3 normal;\n"

"} attr_out;\n"
"void main()\n"
"{ \n"
"    gl_Position = model_view_projection*position;\n"
"    attr_out.normal=normal;\n"
"    attr_out.tex_coord=tex_coord;\n"
"    //gl_Position = gl_ModelVieProjectionMatrix*position;\n"
"    //gl_Position=gl_ModelViewProjectionMatrix*gl_vertex; \n"
"    //gl_Position=ftransform();\n"
"}\n";

const char* es3_centroid_multisampling_frag = "#version 330\n"
    "// Uniforms\n"
    "layout(std140) uniform Inputs\n"
    "{\n"
    "    mat4 model_view;\n"
    "    mat4 projection;\n"
    "    mat4 model_view_projection;\n"
    "};\n"
    "uniform sampler2D image_texture;\n"
    "// Outputs\n"
    "layout(location=0) out vec4 output_color;\n"
    "// Inputs\n"
    "in VertexAttributes\n"
    "{\n"
    "    smooth centroid vec2 tex_coord;\n"
    "    smooth centroid vec3 normal;\n"
    "} attr_in;\n"
    "void main()\n"
    "{\n"
    "    output_color=texture(image_texture,attr_in.tex_coord).xyzw;\n"
    "    // Debugging\n"
    "    /*\n"
    "    output_color=vec4(0.0);\n"
    "    if(smooth_tex_coord.x<0.0)\n"
    "    {\n"
    "        output_color+=vec4(-10,0,0,0);\n"
    "    }\n"
    "    if(smooth_tex_coord.y<0.0)\n"
    "    {\n"
    "        output_color+=vec4(0,smooth_tex_coord.y,0,0);\n"
    "    }\n"
    "    if(smooth_tex_coord.x>1.0)\n"
    "    {\n"
    "        output_color+=vec4(0,0,10,0);\n"
    "    }\n"
    "    if(smooth_tex_coord.y>1.0)\n"
    "    {\n"
    "        output_color+=vec4(0,0,0,10);\n"
    "    }\n"
    "    */\n"
    "}\n";

}


