



// ******** This file is autogenerated. *********



// Note we don't use the Q_DECLARE_METATYPE() or the Q_ENUM() macro because we may eventually
// move away from qml to javascript/typescript oriented gui framework, where we want our json
// message to only contain pure javascript primitive types.

declare const enum ReceiverType {
  kUnknown = 0,
  kWebDriver = 1,
  kChrome = 2,
  kPlatform = 3,
  kFirebase = 4,
}

declare const enum WebDriverRequestType {
  kUnknownWebDriverRequest = 0,

  // Service Requests.
  kStartService = 1,
  kStopService = 2,

  // Browser Requests.
  kIsBrowserOpen = 3,
  kOpenBrowser = 4,
  kOpenBrowserPost = 5,
  kCloseBrowser = 6,
  kReleaseBrowser = 7,
  kSetBrowserSize = 8,
  kGetBrowserSize = 9,

  // Web Page Navigation.
  kNavigateTo = 10,
  kNavigateBack = 11,
  kNavigateForward = 12,
  kNavigateRefresh = 13,
  kGetCurrentURL = 14,

  // Web Page Tabs.
  kUpdateCurrentTab = 15,
  kDestroyCurrentTab = 16,

  // Actions.
  kPerformMouseAction = 17,
  kPerformTextAction = 18,
  kPerformElementAction = 19,
  kPerformImageAction = 20,
}

declare const enum ChromeRequestType {
  kUnknownChromeRequest = 0,

  // Cookies.
  kClearAllCookies = 1,
  kGetAllCookies = 2,
  kSetAllCookies = 3,

  // Zoom.
  kGetZoom = 4,
  kSetZoom = 5,

  // Event Control.
  kBlockEvents = 6,
  kUnblockEvents = 7,
  kWaitUntilLoaded = 8,

  // Tabs.
  kUpdateCurrentTab = 9,
  kOpenTab = 10,
  kGetActiveTabTitle = 11,

  // Element Overlays. These simply act as highlights in the browser.
  kHighlightElements = 12,
  kUpdateElementHighlights = 13,
  kClearElementHighlights = 14,

  // Scrolling.
  kScrollElementIntoView = 15,
  kScrollElement = 16,

  // Others.
  kGetAllElements = 17,
  kUpdateFrameOffsets = 18,
  kReleaseBrowser = 19,
}

declare const enum PlatformRequestType {
  kUnknownPlatformRequest = 0,
  kAcceptSaveDialog = 1,
  kDownloadVideo = 2,
}

declare const enum FirebaseRequestType {
  kFirebaseInit = 0,
  kFirebaseDestroy = 1,
  kFirebaseSignIn = 2,
  kFirebaseSignOut = 3,
  kFirebaseWriteData = 4,
  kFirebaseReadData = 5,
  kFirebaseSubscribe = 6,
  kFirebaseUnsubscribe = 7
}

declare const enum MouseActionType {
  kSendClick = 0,
  kSendCtrlClick = 1,
  kMouseOver = 2
}

declare const enum TextActionType {
  kSendText = 0,
  kSendEnter = 1
}

declare const enum ElementActionType {
  kChooseOption = 0
}

declare const enum ImageActionType {
  kGetImageURL = 0,
  kDownloadImage = 1,
}

declare const enum InfoType {
  kPageIsLoading = 0,
  kPageIsReady = 1,
  kBgIsConnected = 2,
  kShowWebActionMenu = 3,
  kTabCreated = 4,
  kTabDestroyed = 5,
  kCollectFrameIndexPaths = 6,
  kCollectFrameOffsets = 7,
  kDistributeFrameOffsets = 8
}

declare const enum MessageType {
  kUnformedMessage = 0,
  kRequestMessage = 1,
  kResponseMessage = 2,
  kInfoMessage = 3
}

declare const enum ElementType {
  kText = 0,
  kImage = 1,
  kInput = 2,
  kSelect = 3
}

declare const enum DirectionType {
  kLeft = 0,
  kRight = 1,
  kUp = 2,
  kDown = 3
}

declare const enum HTTPSendType {
  kGet = 0,
  kPost = 1,
  kPut = 2,
  kDelete = 3,
  kPatch = 4
}




declare const enum LicenseEdition {
  kLite = 0,
  kPro = 1
}


